/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Post controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, PostDto, PostSortFieldSortParameter, PostFilterFieldFilterParameter, PostDtoPageDto } from "../models";

@Injectable({ providedIn: "root" })
export class PostService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    apiV1PostsIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<PostDto>;
    apiV1PostsIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PostDto>>;
    apiV1PostsIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PostDto>>;
    apiV1PostsIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/posts/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiV1PostsIdPut(id: string, requestBody?: any, observe?: 'body', options?: RequestOptions<'json'>): Observable<PostDto>;
    apiV1PostsIdPut(id: string, requestBody?: any, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PostDto>>;
    apiV1PostsIdPut(id: string, requestBody?: any, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PostDto>>;
    apiV1PostsIdPut(id: string, requestBody?: any, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/posts/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, requestBody, requestOptions);
    }

    apiV1PostsIdDelete(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiV1PostsIdDelete(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiV1PostsIdDelete(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiV1PostsIdDelete(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/posts/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }

    apiV1PostsPageGet(pageIndex: number, pageSize: number, searchTerm?: string, sort?: Array<PostSortFieldSortParameter>, filters?: Array<PostFilterFieldFilterParameter>, observe?: 'body', options?: RequestOptions<'json'>): Observable<PostDtoPageDto>;
    apiV1PostsPageGet(pageIndex: number, pageSize: number, searchTerm?: string, sort?: Array<PostSortFieldSortParameter>, filters?: Array<PostFilterFieldFilterParameter>, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PostDtoPageDto>>;
    apiV1PostsPageGet(pageIndex: number, pageSize: number, searchTerm?: string, sort?: Array<PostSortFieldSortParameter>, filters?: Array<PostFilterFieldFilterParameter>, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PostDtoPageDto>>;
    apiV1PostsPageGet(pageIndex: number, pageSize: number, searchTerm?: string, sort?: Array<PostSortFieldSortParameter>, filters?: Array<PostFilterFieldFilterParameter>, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/posts/page`;

        let params = new HttpParams();
        if (pageIndex != null) {
            params = HttpParamsBuilder.addToHttpParams(params, pageIndex, 'PageIndex');
        }
        if (pageSize != null) {
            params = HttpParamsBuilder.addToHttpParams(params, pageSize, 'PageSize');
        }
        if (searchTerm != null) {
            params = HttpParamsBuilder.addToHttpParams(params, searchTerm, 'SearchTerm');
        }
        if (sort != null) {
            params = HttpParamsBuilder.addToHttpParams(params, sort, 'Sort');
        }
        if (filters != null) {
            params = HttpParamsBuilder.addToHttpParams(params, filters, 'Filters');
        }

        const requestOptions: any = {
            observe: observe as any,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiV1PostsPost(requestBody?: any, observe?: 'body', options?: RequestOptions<'json'>): Observable<PostDto>;
    apiV1PostsPost(requestBody?: any, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PostDto>>;
    apiV1PostsPost(requestBody?: any, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PostDto>>;
    apiV1PostsPost(requestBody?: any, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/posts`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, requestBody, requestOptions);
    }
}
