/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Zod Schemas for Post
* Do not edit this file manually
*/
import { z } from "zod";
export const apiV1PostsGetParams = z.object({
    "id": z.string().uuid()
});
export type ApiV1PostsGetParams = z.infer<typeof apiV1PostsGetParams>;
export const apiV1PostsGet200Response = z.object({
    "id": z.string().uuid().optional(),
    "title": z.string().nullish(),
    "content": z.string().nullish(),
    "slug": z.string().nullish(),
    "createdAt": z.date().optional(),
    "updatedAt": z.date().optional()
});
export type ApiV1PostsGet200Response = z.infer<typeof apiV1PostsGet200Response>;
export const apiV1PostsPutParams = z.object({
    "id": z.string().uuid()
});
export type ApiV1PostsPutParams = z.infer<typeof apiV1PostsPutParams>;
export const apiV1PostsPutBody = z.any();
export type ApiV1PostsPutBody = z.infer<typeof apiV1PostsPutBody>;
export const apiV1PostsPut200Response = z.object({
    "id": z.string().uuid().optional(),
    "title": z.string().nullish(),
    "content": z.string().nullish(),
    "slug": z.string().nullish(),
    "createdAt": z.date().optional(),
    "updatedAt": z.date().optional()
});
export type ApiV1PostsPut200Response = z.infer<typeof apiV1PostsPut200Response>;
export const apiV1PostsDeleteParams = z.object({
    "id": z.string().uuid()
});
export type ApiV1PostsDeleteParams = z.infer<typeof apiV1PostsDeleteParams>;
export const apiV1PostsPageGetQueryParams = z.object({
    "PageIndex": z.number().int(),
    "PageSize": z.number().int(),
    "SearchTerm": z.string().optional(),
    "Sort": z.array(z.object({
        "field": z.any().optional(),
        "orderBy": z.any().optional(),
        "priority": z.number().int().optional()
    })).optional().describe('JSON array of SortParameter objects'),
    "Filters": z.array(z.object({
        "field": z.any().optional(),
        "operator": z.any().optional(),
        "value": z.string().nullish()
    })).optional().describe('JSON array of SortParameter objects')
});
export type ApiV1PostsPageGetQueryParams = z.infer<typeof apiV1PostsPageGetQueryParams>;
export const apiV1PostsPageGet200Response = z.object({
    "items": z.array(z.object({
        "id": z.string().uuid().optional(),
        "title": z.string().nullish(),
        "content": z.string().nullish(),
        "slug": z.string().nullish(),
        "createdAt": z.date().optional(),
        "updatedAt": z.date().optional()
    })).nullish(),
    "pageData": z.any().nullish()
});
export type ApiV1PostsPageGet200Response = z.infer<typeof apiV1PostsPageGet200Response>;
export const apiV1PostsPostBody = z.any();
export type ApiV1PostsPostBody = z.infer<typeof apiV1PostsPostBody>;
export const apiV1PostsPost201Response = z.object({
    "id": z.string().uuid().optional(),
    "title": z.string().nullish(),
    "content": z.string().nullish(),
    "slug": z.string().nullish(),
    "createdAt": z.date().optional(),
    "updatedAt": z.date().optional()
});
export type ApiV1PostsPost201Response = z.infer<typeof apiV1PostsPost201Response>;
