/* @ts-nocheck */

/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export enum FilterOperator {
    Equals = "Equals",
    NotEquals = "NotEquals",
    Contains = "Contains",
    GreaterThan = "GreaterThan",
    LessThan = "LessThan",
    GreaterThanOrEqual = "GreaterThanOrEqual",
    LessThanOrEqual = "LessThanOrEqual",
    In = "In"
}

export enum OrderBy {
    Asc = "Asc",
    Desc = "Desc"
}

export interface PageDataDto {
    pageIndex: number;
    totalPages: number;
    totalCount: number;
    hasPreviousPage: boolean;
    hasNextPage: boolean;
}

export interface PostCreateDto {
    title: string;
    content: string;
    slug?: string;
}

export interface PostDto {
    id: string;
    title: string;
    content: string;
    slug: string;
    createdAt: Date;
    updatedAt: Date;
}

export interface PostDtoPageDto {
    items: Array<PostDto>;
    pageData: PageDataDto;
}

export enum PostFilterField {
    Title = "Title",
    Content = "Content",
    CreatedAt = "CreatedAt",
    UpdatedAt = "UpdatedAt"
}

export interface PostFilterFieldFilterParameter {
    field: PostFilterField;
    operator: FilterOperator;
    value: string | null;
}

export enum PostSortField {
    Title = "Title",
    CreatedAt = "CreatedAt",
    UpdatedAt = "UpdatedAt"
}

export interface PostSortFieldSortParameter {
    field: PostSortField;
    orderBy: OrderBy;
    priority: number;
}

export interface PostUpdateDto {
    title?: string;
    content?: string;
    slug?: string;
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
