/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* `httpResource` is still an experimental feature - NOT PRODUCTION READY
* Generated Angular service for PostResource
* Do not edit this file manually
*/
import { HttpContext, HttpContextToken, HttpHeaders, HttpParams, httpResource, HttpResourceOptions, HttpResourceRef, HttpResourceRequest } from "@angular/common/http";
import { inject, Injectable, Signal } from "@angular/core";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { PostDto, PostSortFieldSortParameter, PostFilterFieldFilterParameter, PostDtoPageDto } from "../models";

@Injectable({ providedIn: "root" })
export class PostResource {
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    apiV1PostsIdGet(id: Signal<string> | string, resourceOptions: HttpResourceOptions<PostDto, unknown> & { defaultValue: NoInfer<PostDto> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<PostDto>;
    apiV1PostsIdGet(id: Signal<string> | string, resourceOptions?: HttpResourceOptions<PostDto, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<PostDto | undefined>;
    apiV1PostsIdGet(id: Signal<string> | string, resourceOptions?: HttpResourceOptions<PostDto, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<PostDto | undefined> {
        return httpResource(() => {
            return {
                url: `${this.basePath}/api/v1/posts/${typeof id === 'function' ? id() : id}`,
                method: "GET",
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }

    apiV1PostsPageGet(pageIndex: Signal<number> | number, pageSize: Signal<number> | number, searchTerm: Signal<string | undefined> | string | undefined, sort: Signal<Array<PostSortFieldSortParameter> | undefined> | Array<PostSortFieldSortParameter> | undefined, filters: Signal<Array<PostFilterFieldFilterParameter> | undefined> | Array<PostFilterFieldFilterParameter> | undefined, resourceOptions: HttpResourceOptions<PostDtoPageDto, unknown> & { defaultValue: NoInfer<PostDtoPageDto> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<PostDtoPageDto>;
    apiV1PostsPageGet(pageIndex: Signal<number> | number, pageSize: Signal<number> | number, searchTerm?: Signal<string | undefined> | string, sort?: Signal<Array<PostSortFieldSortParameter> | undefined> | Array<PostSortFieldSortParameter>, filters?: Signal<Array<PostFilterFieldFilterParameter> | undefined> | Array<PostFilterFieldFilterParameter>, resourceOptions?: HttpResourceOptions<PostDtoPageDto, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<PostDtoPageDto | undefined>;
    apiV1PostsPageGet(pageIndex: Signal<number> | number, pageSize: Signal<number> | number, searchTerm?: Signal<string | undefined> | string, sort?: Signal<Array<PostSortFieldSortParameter> | undefined> | Array<PostSortFieldSortParameter>, filters?: Signal<Array<PostFilterFieldFilterParameter> | undefined> | Array<PostFilterFieldFilterParameter>, resourceOptions?: HttpResourceOptions<PostDtoPageDto, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<PostDtoPageDto | undefined> {
        return httpResource(() => {
            let params = new HttpParams();
            const pageIndexValue = typeof pageIndex === 'function' ? pageIndex() : pageIndex;
            if (pageIndexValue != null) {
                params = HttpParamsBuilder.addToHttpParams(params, pageIndexValue, 'PageIndex');
            }
            const pageSizeValue = typeof pageSize === 'function' ? pageSize() : pageSize;
            if (pageSizeValue != null) {
                params = HttpParamsBuilder.addToHttpParams(params, pageSizeValue, 'PageSize');
            }
            const searchTermValue = typeof searchTerm === 'function' ? searchTerm() : searchTerm;
            if (searchTermValue != null) {
                params = HttpParamsBuilder.addToHttpParams(params, searchTermValue, 'SearchTerm');
            }
            const sortValue = typeof sort === 'function' ? sort() : sort;
            if (sortValue != null) {
                params = HttpParamsBuilder.addToHttpParams(params, sortValue, 'Sort');
            }
            const filtersValue = typeof filters === 'function' ? filters() : filters;
            if (filtersValue != null) {
                params = HttpParamsBuilder.addToHttpParams(params, filtersValue, 'Filters');
            }
            return {
                url: `${this.basePath}/api/v1/posts/page`,
                method: "GET",
                params,
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }
}
